apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    severity: {{ .Values.responsible.severity }}
    owner: {{ .Values.responsible.owner }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      name: {{ .Chart.Name }}-port
  selector:
    app: {{ .Chart.Name }}
