# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mlflow-local
  # !!! change to Always
  pullPolicy: IfNotPresent 
  # Overrides the image tag whose default is the chart appVersion.
  # !!! delete tag value to use latest
  tag: "v001"

service:
  type: LoadBalancer
  port: 5000
  target_port: 5000

podAnnotations: {}

# mlflow specific values
aws_access:
  access_key_id: "" # key
  secret_access_key_id: "" # key

default_artifact_root: "s3://mlflow-k8s-local/artifacts"

db:
  type: postgresql
  host: mlflow-rds-inst.cyr4nb3nsigd.eu-west-1.rds.amazonaws.com
  port: 5432
  user: mlflow_user
  password: # pass for db
  database: mlflow_db

# owner to contact and priority
responsible:
  severity: "medium"
  owner: "ykhvainitski"